inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - "rubocop-md"
  - "rubocop-packaging"
  - "rubocop-rake"

Layout/ExtraSpacing:
  Exclude: 
    - "**/lib/sevgi/standard/**/*.rb"
    - "**/test/**/*.rb"
Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 140
  Exclude: 
    - "**/test/**/*.rb"
Layout/MultilineArrayLineBreaks:
  Exclude: 
    - "**/test/**/*.rb"
Layout/MultilineMethodArgumentLineBreaks:
  Exclude: 
    - "**/test/**/*.rb"
Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - "**/test/**/*.rb"
    - "*.gemspec"
    - "**/srv/examples/**/*.sevgi"
Metrics/ClassLength:
  Exclude: 
    - "**/test/**/*.rb"
    - "**/srv/examples/**/*.sevgi"
Metrics/MethodLength:
  Exclude: 
    - "**/test/**/*.rb"
    - "**/srv/examples/**/*.sevgi"

Naming/MethodName:
  Enabled: false

Minitest/UselessAssertion:
  Exclude:
    - "**/test/test_common.rb" # TODO: to avoid a bug

Rails/RefuteMethods:
  Enabled: false
      
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude: 
    - "**/test/**/*.rb"
Style/Documentation:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Exclude: 
    - "**/test/**/*.rb"
    - "**/srv/examples/**/*.sevgi"
Style/ParallelAssignment:
  Enabled: false
Style/SymbolArray:
  Exclude: 
    - "**/lib/sevgi/standard/**/*.rb"
    - "**/test/**/*.rb"
Style/SymbolLiteral:
  Exclude: 
    - "**/lib/sevgi/standard/**/*.rb"
    - "**/test/**/*.rb"
Style/TrailingCommaInArguments:
  Exclude: 
    - "**/test/**/*.rb"

AllCops:
  NewCops: enable
  Include:
    - "**/srv/examples/**/*.sevgi"
  Exclude:
    - "vendor/**/*"
    - "_/**/*"
    - "**/_/**/*"
