# frozen_string_literal: true

require_relative "mixtures/core"

require_relative "mixtures/call"
require_relative "mixtures/duplicate"
require_relative "mixtures/hatch"
require_relative "mixtures/identify"
require_relative "mixtures/include"
require_relative "mixtures/inkscape"
require_relative "mixtures/lint"
require_relative "mixtures/polyfills"
require_relative "mixtures/print"
require_relative "mixtures/rdf"
require_relative "mixtures/render"
require_relative "mixtures/save"
require_relative "mixtures/symbols"
require_relative "mixtures/tile"
require_relative "mixtures/transform"
require_relative "mixtures/underscore"
require_relative "mixtures/validate"
require_relative "mixtures/wrappers"
