# frozen_string_literal: true

$LOAD_PATH.push(File.expand_path("lib", __dir__))

require "sevgi/showcase"

ENV["PATH"] += ":#{::File.expand_path("bin")}" if ::Dir.exist?("bin")

# test

require "rake/testtask"

desc "Run unit tests"
Rake::TestTask.new(:test) do |t|
  t.test_files = FileList["test/**/*_test.rb"].exclude(/(^[._]|integration)/)
end

if ::File.exist?("test/integration_test.rb")
  desc "Run integration tests"
  Rake::TestTask.new(:integration) do |t|
    t.test_files = [ "test/integration_test.rb" ]
  end

  desc "Run all tests"
  Rake::Task[:test].enhance(%i[ integration ])
end

# lint

require "rubocop/rake_task"
RuboCop::RakeTask.new(:rubocop) do |t|
  t.options = [ "--display-cop-names" ]
end

desc "Lint code"
task lint: :rubocop

# pack

task :package if ::Dir["*.gemspec"].any?

# site

COLOR = {
  "black"   => "white",
  "#000"    => "#fff",
  "#000000" => "#ffffff",
}

if ::Dir.exist?("srv")
  desc "Build site showcase"
  task :"site:showcase" do
    warn "...Building masters"
    (bins = Sevgi::Test::Suite.new("srv").valids.map(&:file)).each do |bin|
      warn "   #{File.basename(bin, ".*")}"
      sh bin, verbose: false
    end

    bins.map! { ::File.expand_path(it) }

    warn "...Building lights"
    Dir.chdir("doc/showcase/light") do
      bins.each do |bin|
        warn "   #{File.basename(bin, ".*")}"
        [ bin, bin.ext("svg") ].each { cp it, ".", verbose: false }
      end
    end

    warn "...Building darks"
    Dir.chdir("doc/showcase/dark") do
      bins.each do |bin|
        warn "   #{File.basename(bin, ".*")}"

        target = File.basename(bin)
        content = ::File.read(bin)
        COLOR.each do |key, value|
          content.gsub!(/(['"])#{Regexp.escape(key)}\1/, "\\1#{value}\\1")
        end
        File.write(target, content)
        File.chmod(0777, target)
        sh "./#{target}", verbose: false
      end
    end
  end

  desc "Build site"
  task :"site:build" do
    Dir.chdir("doc") { sh "zola build" }
  end

  desc "Serve site"
  task :"site:serve" do
    require 'socket'

    ip = Socket.ip_address_list.reject( &:ipv6? ).reject!(&:ipv4_loopback?).first.ip_address

    Dir.chdir("doc") do
      sh(*%W[
        zola serve --interface 0.0.0.0 --base-url http://#{ip}
      ])
    end
  end

  task serve: [ :"site:serve" ]
  task s:     [ :"site:serve" ]
end

# clean

require "rake/clean"
CLEAN.include("*.gem", "pkg", "coverage")

# default

task default: [ :test ]

task all:     %i[lint test]
