# frozen_string_literal: true

require "socket"
require "yaml"

$LOAD_PATH.push(File.expand_path("lib", __dir__))

require "sevgi/showcase"
require "sevgi/showcase/dark"
require "sevgi/showcase/minitest"

showcase_dark = Sevgi::Showcase.const_get(:Dark, false)
showcase_test = Sevgi::Showcase.const_get(:Test, false)

ENV["PATH"] = [ENV["PATH"], ::File.expand_path("bin")].compact.join(::File::PATH_SEPARATOR) if ::Dir.exist?("bin")

# Test

require "rake/testtask"

desc("Run unit tests")
Rake::TestTask.new(:test) do |t|
  t.test_files = FileList["test/**/*_test.rb"].exclude(/(^[._]|integration|browser)/)
end

desc("Run real-browser documentation tests")
Rake::TestTask.new(:browser) do |t|
  t.test_files = FileList["test/**/*browser_test.rb"]
end

if ::File.exist?("test/integration_test.rb")
  desc("Run integration tests")
  Rake::TestTask.new(:integration) do |t|
    t.test_files = ["test/integration_test.rb"]
  end

  desc("Run all tests")
  Rake::Task[:test].enhance(%i[integration])
end

# Lint

rubocop_root = File.expand_path("..", Dir.pwd)
rubocop_target = File.basename(Dir.pwd)

task(:rubocop) do
  Dir.chdir(rubocop_root) do
    sh("bundle", "exec", "rubocop", rubocop_target, "--display-cop-names")
  end
end

desc("Lint code")
task(lint: :rubocop)

# Pack

task(:package) if ::Dir["*.gemspec"].any?

# Site

def say(sign, subject) = warn("#{sign} #{::File.basename(subject, ".*")}")

if ::Dir.exist?("srv")
  bins = showcase_test::Suite.new("srv").valids

  bins.map do |bin|
    file(bin.svg => bin.file) do |t|
      say(">>>", t.name)

      sh([t.source, t.source], verbose: false)
    end

    bin.svg
  end => masters

  desc("Build showcase")
  task("site:showcase:masters": masters) do
    warn("")
    warn("=== Showcase masters done.")
    warn("")
  end

  "doc/showcase/light".tap do |dir|
    files = []

    bins.each do |bin|
      file((target = ::File.expand_path("#{dir}/#{bin.file!}")) => bin.file) do |t|
        say(">>>", t.name)

        cp(t.source, t.name, verbose: false)
      end

      files << target

      file((target = ::File.expand_path("#{dir}/#{bin.svg!}")) => bin.svg) do |t|
        say(">>>", t.name)

        cp(t.source, t.name, verbose: false)
      end

      files << target
    end

    desc("Build light showcase")
    task("site:showcase:light": files) do
      warn("")
      warn("=== Showcase lights done.")
      warn("")
    end
  end

  "doc/showcase/dark".tap do |dir|
    files = []

    bins.each do |bin|
      file((target = ::File.expand_path("#{dir}/#{bin.file!}")) => [bin.file, bin.yml]) do |t|
        if File.exist?(cfg = bin.yml) && (yaml = YAML.load_file(cfg)) && (color = yaml["dark"])
          say("***", t.name)

          showcase_dark.apply_file(t.source, t.name, color)
        else
          say(">>>", t.name)

          cp(t.source, t.name, verbose: false)
        end
      end

      files << target

      source = target

      file((target = ::File.expand_path("#{dir}/#{bin.svg!}")) => source) do |t|
        say("...", t.name)

        sh([t.source, t.source], verbose: false)
      end

      files << target
    end

    desc("Build dark showcase")
    task("site:showcase:dark": files) do
      warn("")
      warn("=== Showcase darks done.")
      warn("")
    end
  end

  desc("Build showcase")
  task("site:showcase": [:"site:showcase:masters", :"site:showcase:light", :"site:showcase:dark"])

  desc("Build site")
  task(:"site:build") do
    Dir.chdir("doc") { sh("zola", "build") }
  end

  desc("Serve site")
  task(:"site:serve") do
    ip = Socket.ip_address_list.reject(&:ipv6?).reject!(&:ipv4_loopback?).first.ip_address

    Dir.chdir("doc") do
      sh(
        *%W[
          zola
          serve
          --interface
          0.0.0.0
          --base-url
          http://#{ip}
        ]
      )
    end
  end

  task(serve: [:"site:serve"])
  task(s: [:"site:serve"])
  task(ss: [:"site:showcase"])
end

# Clean

require "rake/clean"

CLEAN.include("*.gem", "pkg")

# Default

task(default: [:test])

task(all: %i[lint test])
