# Zola configuration for Sevgi documentation
base_url                   = "https://sevgi.roktas.dev/"
title                      = "Sevgi"
build_search_index         = true
[markdown]
insert_anchor_links        = "heading"
[markdown.highlighting]
style                      = "class"
light_theme                = "github-light"
dark_theme                 = "github-dark"
[extra]
logo_name                  = "Sevgi"
logo_path                  = "/img/logo-mark.png"
github_repo                = "roktas/sevgi"
site_description           = "Toolkit to create SVG content with Ruby."
nav_groups                 = ["Start", "Core", "Toolkit", "More"]
extra_menu                 = [
  { title = "API", link = "https://www.rubydoc.info/gems/sevgi" },
]
