# frozen_string_literal: true

require "fileutils"
require "tempfile"

module Sevgi
  module Sundries
    module Export
      # Places a single A5 PDF page twice on an A4 landscape sheet with pdfcpu.
      # @param infile [String] source PDF file path
      # @param outfile [String] destination PDF file path
      # @return [Sevgi::Function::Shell::Result] command result
      # @raise [Sevgi::Error] when pdfcpu is missing or the command fails
      # @raise [Errno::ENOENT] when the executable cannot be spawned
      # @see https://pdfcpu.io/ pdfcpu
      def a5_on_a4(infile, outfile) = F.sh!("pdfcpu", "nup", "--", "form:A4L, border:off", outfile, "2", infile)

      # Replaces a PDF file with an A5-on-A4 layout generated by pdfcpu.
      # @param infile [String] PDF file path to modify
      # @return [void]
      # @raise [Sevgi::Error] when pdfcpu is missing or the command fails
      # @raise [Errno::ENOENT] when the executable cannot be spawned
      def a5_on_a4!(infile)
        temp = Tempfile.new(%w[output .pdf], File.dirname(infile))
        a5_on_a4(infile, temp.path)
        FileUtils.mv(temp.path, infile)
      ensure
        temp&.close!
      end

      # Exports an SVG file through Inkscape.
      # @param infile [String] source SVG file path
      # @param outfile [String, nil] output path, defaulting to infile with a .pdf extension
      # @param format [Symbol, String, nil] explicit output format, or nil to infer from outfile
      # @param background [String, nil] export background color
      # @param opacity [Numeric, nil] export background opacity
      # @param width [Numeric, nil] target export width
      # @param height [Numeric, nil] target export height
      # @param id [String, nil] SVG element id to export
      # @param page [Integer, String, nil] page selector passed to Inkscape
      # @param css [String, nil] CSS inserted before exporting
      # @return [Sevgi::Function::Shell::Result] command result
      # @raise [Sevgi::Sundries::Export::ExportError] when format or output extension is unsupported
      # @raise [Sevgi::Error] when Inkscape is missing or the command fails
      # @raise [Errno::ENOENT] when the executable cannot be spawned
      # @see https://inkscape.org/ Inkscape
      def inkscape(
        infile,
        outfile = nil,
        format: nil,
        background: "#ffffff",
        opacity: 1,
        width: nil,
        height: nil,
        id: nil,
        page: nil,
        css: nil
      )
        infile = File.expand_path(infile)
        outfile ||= F.subext(".pdf", infile)
        outfile = File.expand_path(outfile)
        format = format_for!(format, outfile)

        if css
          temp = Tempfile.new(%w[input .svg], File.dirname(infile))
          ::File.write(temp.path, inject(::File.read(infile), css))
          infile = temp.path
        end

        F.sh!(
          *[
            "inkscape",
            "--batch-process",
            "--actions=select-by-class:text,object-to-path",
            "--export-type=#{format}",
            ("--export-background=#{background}" if background),
            ("--export-background-opacity=#{opacity}" if opacity),
            ("--export-width=#{width}" if width),
            ("--export-height=#{height}" if height),
            ("--export-id=#{id}" if id),
            ("--export-id-only" if id),
            ("--export-page=#{page}" if page),
            "--export-filename=#{outfile}",
            infile
          ].compact
        )
      ensure
        temp&.close!
      end

      # Exports an SVG file through rsvg-convert.
      # @param infile [String] source SVG file path
      # @param outfile [String, nil] output path, defaulting to infile with a .pdf extension
      # @param format [Symbol, String, nil] explicit output format, or nil to infer from outfile
      # @param background [String, nil] export background color
      # @param width [Numeric, nil] target export width
      # @param height [Numeric, nil] target export height
      # @param id [String, nil] SVG element id to export
      # @param css [String, nil] CSS inserted before exporting
      # @return [Sevgi::Function::Shell::Result] command result
      # @raise [Sevgi::Sundries::Export::ExportError] when format or output extension is unsupported
      # @raise [Sevgi::Error] when rsvg-convert is missing or the command fails
      # @raise [Errno::ENOENT] when the executable cannot be spawned
      # @see https://gitlab.gnome.org/GNOME/librsvg librsvg
      def rsvg(
        infile,
        outfile = nil,
        format: nil,
        background: "#ffffff",
        width: nil,
        height: nil,
        id: nil,
        css: nil
      )
        infile = File.expand_path(infile)
        outfile ||= F.subext(".pdf", infile)
        outfile = File.expand_path(outfile)
        format = format_for!(format, outfile)

        if css
          temp = Tempfile.new(%w[input .svg], File.dirname(infile))
          ::File.write(temp.path, inject(::File.read(infile), css))
          infile = temp.path
        end

        F.sh!(
          *[
            "rsvg-convert",
            "--format=#{format}",
            ("--background-color=#{background}" if background),
            ("--width=#{width}" if width),
            ("--height=#{height}" if height),
            ("--export-id=#{id}" if id),
            "--output=#{outfile}",
            infile
          ].compact
        )
      ensure
        temp&.close!
      end

      # Merges PDF files with pdfunite.
      # @param sources [Array<String>] source PDF file paths
      # @param outfile [String] destination PDF file path
      # @return [Sevgi::Function::Shell::Result] command result
      # @raise [Sevgi::Error] when pdfunite is missing or the command fails
      # @raise [Errno::ENOENT] when the executable cannot be spawned
      # @see https://poppler.freedesktop.org/ Poppler
      def unite(sources, outfile) = F.sh!("pdfunite", *sources, outfile)

      extend self
    end
  end
end
