# frozen_string_literal: true

require "rake/clean"
require "rake/testtask"

$LOAD_PATH.unshift(File.expand_path("lib", __dir__))

desc("Run unit tests")
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.pattern = "test/**/*_test.rb"
end

rubocop_root = File.expand_path("..", __dir__)

task(:rubocop) do
  Dir.chdir(rubocop_root) do
    sh("bundle", "exec", "rubocop", "appendix", "--display-cop-names")
  end
end

desc("Lint code")
task(lint: :rubocop)

task(:package)

CLEAN.include("*.gem", "pkg")

task(default: :test)
task(all: %i[lint test])
