name: Site
on:
  push:
    branches: ["main"]
    paths:
      - "showcase/doc/**"
      - ".github/workflows/site.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "showcase/doc/**"
      - ".github/workflows/site.yml"
  workflow_dispatch:
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Deploy 🥁
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          BUILD_DIR: showcase/doc
          PAGES_BRANCH: site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
