name: Test
on:   [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.4", "4.0.6"]
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
    - name: Native dependencies 🧱
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libgdk-pixbuf-2.0-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          librsvg2-dev \
          pkg-config
    - name: Ruby 🥁
      uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Unit 🔬
      run: bundle exec rake test
    - name: API docs 📚
      run: bundle exec rake doc:check
    - name: Upload API docs 📚
      if: matrix.ruby == '4.0.6'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: api-docs
        path: .cache/ruby/doc/api
    - name: Build 📦
      run: bundle exec rake build
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
    - name: Native dependencies 🧱
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libgdk-pixbuf-2.0-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          librsvg2-dev \
          pkg-config
    - name: Ruby 🥁
      uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
      with:
        ruby-version: "4.0.6"
        bundler-cache: true
    - name: Coverage 🧮
      run: bundle exec rake coverage
    - name: Upload coverage 🧮
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: coverage
        path: .cache/ruby/coverage
